### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by onodera-punpun** [kisslinux/website#12]
Does KISS have an IRC channel, if so, can some info be added to the website, if not, can one possible be created?

**Comment by dylanaraps** [comment]
I'm looking into it. We currently use a Discord server but have wanted to explore a privacy-respecting alternative for a while now. Any suggestions on IRC networks?

**Comment by onodera-punpun** [comment]
freenode seems to be the goto for most distros and software projects

**Comment by dylanaraps** [comment]
I've sent an email to Freenode about securing `#kisslinux`. :+1:

**Comment by onodera-punpun** [comment]
While you are at it, maybe secure `#kisslinux-devel` as well, that is if you intend on using IRC for development talks ;)

**Comment by dylanaraps** [comment]
Still waiting on a reply. Sent an additional email after talking to someone in `#freenode`.

**Comment by dylanaraps** [comment]
Done. :+1:
