### ISSUE TITLE
Install - Enable repository signing: missing keyserver

### ISSUE THREAD

**Issue by iandrewt** [kisslinux/website#20]
On a fresh install, gnupg1 doesn't know about any key servers yet, so running `gpg --recv-key 46D62DD9F1DE636E` results in this error:
```
gpg: no key server known (use option --keyserver)
gpg: keyserver receive failed: bad URI
```
I was able to import the key by specifying the pgp.mit.edu key server

**Comment by dylanaraps** [comment]
Fixed. Thanks :+1:
