### ISSUE TITLE
Requesting details/dotfiles linked for each screenshots

### ISSUE THREAD

**Issue by bluecat999** [kisslinux/website#23]
Hi, great website!

On the screenshot page, there are some images showing a variety of unique setups. I believe it might be helpful to share details about the setup to help any users who wish to quickly create similar setups or adapt components they like.

This could be achieved by replacing the hyperlink to https://github.com/dylanaraps/ with a link to https://github.com/dylanaraps/dotfiles and requesting something similar from other contributors.

**Comment by kiedtl** [comment]
Plus, it would be nice to know what WM the various screenshot-ed desktops are using.

**Comment by dylanaraps** [comment]
GitHub profile links are provided (*if provided to me*) and the overall purpose of the screenshots page isn't to advertise configuration files. I also don't see it as reasonable to round up each person and ask them to provide links to their dotfiles.

Closing this.
