### ISSUE TITLE
Suggestion: do not copy the templates

### ISSUE THREAD

**Issue by st4ll1** [kisslinux/website#25]
Hi, 
i love this approach of minimal site generation.

And i have a suggestion, i guess the .www folder should be copied to the webspace as it is,
so for me it makes no sense that the templates folder is in there too.

Solutions to this that came to my mind are :
(cd ../src; find . -type f -a -not -path '*/\.*' -not -path '*templates/*') 
or simply move the templates folder out of the site folder.

**Comment by dylanaraps** [comment]
Fixed in https://github.com/kisslinux/website/commit/f94d6356834e8aba4695722b8fdc2dfcc0936ebb

Thanks for the suggestion. :+1:
