### ISSUE TITLE
use example.com instead of website.com

### ISSUE THREAD

**Issue by spiralofhope** [kisslinux/website#41]
Edit the page https://k1ss.org/style

```
https://website.com/fix-build.patch
=>
https://example.com/fix-build.patch
```

rationale:

> example.com, example.net, example.org, and example.edu are second-level domain names reserved for documentation purposes and examples of the use of domain names.
> -- https://en.wikipedia.org/wiki/Example.com

(Sorry, I don't know how to use git or github well enough to do a pull request.)

**Comment by dylanaraps** [comment]
Fixed, thanks,
