### ISSUE TITLE
Add a "Post installation" page

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/website#50]
Mention:

- [x] Setting up timezones.
- [ ] Setting up Xorg.
- [x] Setting up Sound.
- [ ] System optmization.
- [ ] Fonts.
- [ ] ...

**Comment by dylanaraps** [comment]
Any suggestions are welcome!

**Comment by jedahan** [comment]
- [ ] Setting up Wayland
- [ ] Setting up bluetooth
- [ ] Modern networking

**Comment by illiliti** [comment]
* [ ] Removing tty1 cluttering triggered by runit services
* [ ] Running Xorg without xinit
* [ ] Autologin to tty
* [ ] Microcode (if possible), wireless regulatory database
* [ ] Automatically saving/restoring audio/brightness via service
* [ ] Dbus-less notifications

**Comment by illiliti** [comment]
* [ ] Xorg hi-dpi (a little bit hacky i know)
* [ ] Keyboard layout(xorg.conf and/or setxkbmap)
* [ ] Decluttering $HOME by patching source (e.g `sed -i 's|\.zshrc|\.config/zsh/rc|' Src/init.c` )

**Comment by sdsddsd1** [comment]
[ - ] `Searching` the git history for e.g netsurf.

**Comment by sdsddsd1** [comment]
[ - ] Examine how to add custom keybindings to a windowmanager with `kiss-fork` and personal config.h

**Comment by sdsddsd1** [comment]
- [ ] Good practice for reporting bugs.
- Problem with packages -> contact the maintainer `kiss-maintainer`.
- Provide logs from actual build. Point at `~/.cache/kiss/logs`.
           Also point at `#!/bin/nc termbin.com:9999`.  

This might be obvious but few guidlines arent too much I think.

**Comment by dylanaraps** [comment]
I'm going to close this and push the majority of the items later today. 

There are some things which I haven't written sections for as I don't believe they belong in the post-installation guide (wayland, finding build logs, maintainer information, using kiss-fork, git history, bug reporting, de-cluttering /home, bluetooth, etc.

Most of these belong in a "package management" page (in a similar style to this one) and others in the replacement to the Wiki which I am also working on.
