### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by AJCM-git** [kisslinux/website#55]
It redirects to `https://github.com/kisslinux/repo/releases/download/1.10.0`, wich gives a 404 error. Github supports automatic redirect to the latest release, with the folowing format: `https://github.com/user-name/repo/releases/latest/download/package`, so it should be something like this: `https://github.com/kisslinux/repo/releases/latest/download/kiss-chroot.tar.xz` (you had the wrong format)

**Comment by dylanaraps** [comment]
The working link is there, we just define a variable `url=` to avoid having it in multiple places.
