### ISSUE TITLE
broken links to kiss-chroot and chroot helper on https://k1ss.org/install

### ISSUE THREAD

**Issue by a-schaefers** [kisslinux/website#57]
The links are broken to kiss-chroot and chroot helper on https://k1ss.org/install

**Comment by dylanaraps** [comment]
All of the links work fine. You need to combine the value of `$url` with the name of the file. Look closer. :+1:

**Comment by a-schaefers** [comment]
Oh my goodness we cannot do anything normal here. Lol. Thanks for letting
me know.
