### ISSUE TITLE
Absolute links in wiki being interpreted as relative links

### ISSUE THREAD

**Issue by noocsharp** [kisslinux/website#58]
All wiki links intended as absolute links are interpreted as relative links by line 14 in the make script. For example, on <https://k1ss.org/wiki/software/git> there is a "@/help/adding-a-page" that should be linking to "/wiki/help/adding-a-page" but is instead linking to "/wiki/software/help/adding-a-page". 

The simplest solution I can think of is treating a link as absolute if the page name is preceded by a directory name, and as relative otherwise. But this would limit the directory depth on the wiki.

**Comment by dylanaraps** [comment]
I've added a new link type which is absolute. :+1:
