### ISSUE TITLE
Web site looks bad with liberation fonts

### ISSUE THREAD

**Issue by FultonBrowne** [kisslinux/website#65]
The liberation fonts are the ones used in the official install instructions https://k1ss.org/install#13.0 yet there seems to be an issue with using this font on the website:
![2020-09-02-183635_1366x768_scrot](https://user-images.githubusercontent.com/50185337/92023002-a680a400-ed4b-11ea-9a37-e7da626c7aa9.png)

BTW, I love the website and kiss is the best distro I've used :]

**Comment by dylanaraps** [comment]
This is an issue with the font you have chosen. Are you sure it's monospace? You can go into the browser's settings to change it as the KISS website uses whatever the user sets. :+1:
