### ISSUE TITLE
What happened to the guidestones?

### ISSUE THREAD

**Issue by AndreiSva** [kisslinux/website#82]
I've noticed the guidestones page has disappeared from kiss linux's website. Are the guidestones being changed? If so, what are the new ones and are there any plans on bringing them back on the website?

The webpage I'm talking about is still viewable on Dilyn's website https://k1sslinux.org/guidestones.

**Comment by dylanaraps** [comment]
I am working on a rewrite of the website's content (for > 1 month now). The guidestones will not return in the same form, however the information will still exist in some kind of equivalency. There is still a lot of work to do, stay tuned.
