### ISSUE TITLE
Patreon information out-of-date

### ISSUE THREAD

**Issue by jedahan** [kisslinux/website#86]
Now that you've re-activated, so did I re-activate my Patreon membership. But the information is a bit out-of-date.

> I am a Greek/Australian developer working on a myriad of projects. Most notably the upcoming Linux distribution called KISS. 
> 
> KISS Linux: https://getkiss.org
> 
> GitHub pages:
> 
> - https://github.com/dylanaraps
> - https://github.com/kisslinux

Maybe something like 

> I am a Greek/Australian developer working on a myriad of projects. Most notably the KISS Linux distribution. 
> 
> KISS Linux: https://kisslinux.org
> 
> GitHub pages:
> 
> - https://github.com/dylanaraps
> - https://github.com/kisslinux

Also, it links to a Discord. Personally, I like the idea of a Discord for people sharing when they code, but that should probably be removed.

**Comment by dylanaraps** [comment]
Done, thanks,

**Comment by jedahan** [comment]
Looks good, though the href for https://dy1an.xyz/arapsware actually links to https://www.patreon.com/edit/https://dy1an.xyz/arapsware for some reason
