### ISSUE TITLE
add references to irc channel and community website

### ISSUE THREAD

**Issue by AndreiSva** [kisslinux/website#88]
I've been browsing the new website (which btw, looks amazing and was a much needed improvement over the old one), and I noticed both the community section of the wiki and the the community repo from the install guide have been removed.

I think it's important to have at least a few links in the wiki about the existing community so new users don't feel lost after completing the initial installation. What is your opinion on this? Would you be open to this?

**Comment by dilyn-corner** [comment]
I understand. We can certainly look into modifying these things to better distinguish ourselves.
