### ISSUE TITLE
Best practice for XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by luizbra** [kisslinux/website#93]
Hey there! What's the best practice for creating the XDG_RUNTIME_DIR? Currently I'm doing this:

     In ~/.profile:
     export XDG_RUNTIME_DIR="/run/user/$(id -u)"
     doas mkdir -p "$XDG_RUNTIME_DIR"
     doas chown "$USER:$USER" "$XDG_RUNTIME_DIR"

Any thoughts?

**Comment by dylanaraps** [comment]
I set it up similarly but at boot time via /etc/rc.d. This directory can be anywhere and I only picked /run as an example. Users are expected to set this to the ideal value for their use case and the only requirement is that it be writable by the applicable user.

Thanks for opening this issue.
