### ISSUE TITLE
"install" contains inconsistent title style

### ISSUE THREAD

**Issue by Riteo** [kisslinux/website#95]
`[027] Install The Modules (To /usr/lib)` and `[028] Install The Kernel Image To (/boot)` are still formatted with the old dashes-fill-spaces style:
![example](https://user-images.githubusercontent.com/31065808/139719671-47be28db-2199-4685-ac12-2606aa935716.png)

Also IMO it'd be more consistent to move the `To` outside of the parentheses in [027]'s title, but that's really an even bigger nitpick.

**Comment by dylanaraps** [comment]
Fixed, thanks.
