### ISSUE TITLE
Github Icon "Invisible" in dark mode

### ISSUE THREAD

**Issue by sourTaste000** [kisslinux/website#96]
It is not really "invisible", it is just hard to find the icon.

Screenshot in dark mode:
<img width="939" alt="Screen Shot 2021-11-12 at 9 51 58 AM" src="https://user-images.githubusercontent.com/47074495/141512317-b9adb2ed-23b4-45a8-9ca7-c9861d9216cd.png">

**Comment by dylanaraps** [comment]
Thanks.
